### ISSUE TITLE
Execute task "jacocoTestReportMerged" failure on Gradle 5.0 

### ISSUE THREAD

**Issue by canglongxiang** [vanniktech/gradle-android-junit-jacoco-plugin#136] opened 2018-12-06 09:42 UTC
Greate plugin for jacaco support!
Everything is ok when using with jacoco 0.8.2, gradle 4.10.2, jdk8 and this plugin 0.13.0.

After upgrade gradle to 5.0, execute task "jacocoTestReportMerged" has below error info:

```
FAILURE: Build failed with an exception.

What went wrong:

java.lang.StackOverflowError (no error message)
```

PS: Task "jacocoTestReport" is ok.

**Comment by vanniktech** [comment] 2018-12-24 10:46
Can you send a proper stacktrace?

**Comment by vanniktech** [comment] 2019-01-03 10:06
I'm closing this issue due to inactivity. If you have any further input on the issue, don't hesitate to reopen this issue or post a new one.

**Comment by pardom** [comment] 2019-01-14 22:56
I'm getting this same exception with this recursion in the stack trace:

```
at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:164)
at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:109)
at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
...
```

Can we reopen this?

**Comment by pardom** [comment] 2019-01-14 23:10
Here's more of the stack trace (my terminal buffer was cutting it off):

```
* Exception is:
java.lang.StackOverflowError
        at org.gradle.util.GUtil.addToCollection(GUtil.java:163)
        at org.gradle.util.GUtil.addToCollection(GUtil.java:174)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:130)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:164)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:109)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
...
```

**Comment by pardom** [comment] 2019-01-15 16:53
I would assume this is related to this: https://github.com/gradle/gradle/issues/7636

**Comment by pardom** [comment] 2019-01-17 16:12
Is https://github.com/gradle/gradle/issues/7636 not enough information to reopen this? Appending to the source directories in this way:

https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/master/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L91-L93

https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/master/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L250-L252

Is the source of the `StackOverflowError`. Rather, the sources should be collected and set once using the additional sources methods or `setFrom` on the `FileCollection`s.

**Comment by vanniktech** [comment] 2019-01-18 10:37
Sure, I can reopen this but it seems like this is something Gradle can/will fix? If you can come up with a solution, feel free to create a PR.

**Comment by pardom** [comment] 2019-01-18 15:22
I'm not sure they're going to fix it on their end: https://github.com/gradle/gradle/issues/7636#issuecomment-436313618

I worked around it by doing:

```groovy
def allFiles = task.fileCollection.files + newFiles
task.fileCollection.setFrom(allFiles)
```

**Comment by vanniktech** [comment] 2019-01-19 13:17
Where have you done that?

**Comment by pardom** [comment] 2019-01-19 13:18
I copied the lastest release's sources (master is broken) into buildSrc.

**Comment by vanniktech** [comment] 2019-01-31 21:08
@pardom have you had time to look into this?

**Comment by vanniktech** [comment] 2019-02-26 09:30
Closed by #151 

Thanks :)

**Closed by vanniktech** 2019-02-26 09:30 UTC
Labels: needs info, pr welcome

**Comment by henriquenfaria** [comment] 2019-04-24 13:00
I'm still getting the StackOverFlow error with the `0.14.0-SNAPSHOT` version.
Ideas?

**Comment by lukas1** [comment] 2020-03-26 12:46
Still facing this issue on 0.16.0

**Comment by lukas1** [comment] 2020-03-26 13:02
This works:
```
./gradlew clean jacocoTestReportDebug mergeJacocoReports jacocoTestReportMerged 
```
this doesn't
```
./gradlew clean jacocoTestReportDebug mergeJacocoReports && ./gradlew jacocoTestReportMerged 
```

**Comment by vanniktech** [comment] 2020-03-26 14:32
Mind submitting a PR?

**Comment by lukas1** [comment] 2020-03-26 15:27
I have not really played with source code of the plugin itself and I've tried to see if Gradle gives any useful error, but it gives nothing, so I have no idea whatsoever, why that would be the case. I have not really dug deep enough.

**Comment by lukas1** [comment] 2020-03-27 20:19
Ok, I'm not sure how deep I'll be able to dig into this, but my preliminary finding is, that it might have something to do with this line:

https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/17cc503f7b242667ddf02588e7c885d4462a15ab/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L289

Commenting this line prevents crash of the build, running:
`./gradlew clean jacocoTestReportDebug mergeJacocoReports && ./gradlew jacocoTestReportMerged `

Also, I'm adding some prints to the start of `jacocoTestReportMerged` task. It looks like this task is run at least twice, once during start(which is weird btw, that it runs during start of the build, since it's the very last task that should have been run), when `mergeTask.destinationFile` doesn't exist yet and then when running the task `jacocoTestReportMerged` after `&&`, the `mergedReport.exec` file already exists, but then it fails somewhere in gradle (I don't have any error message).

Disabling the line that I sent above makes the task succeed, but obviously nothing is happening.

I'm not sure if it's incorrect contents of the report file, because I don't know how to verify that.

**Comment by lukas1** [comment] 2020-03-29 19:06
ok bit more information and since I'm really not knowledgable about writing gradle plugins or using JaCoCo very much, I could probably also use some help. I've localised the problem to this line:
https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/feb9fa425951617caebe453d5661c9c655146004/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L260

```
mergedReportTask.classDirectories.setFrom(classDirectories.getFrom() + mergedReportTask.classDirectories.getFrom())
```

now, if I change this line to this:

```
mergedReportTask.classDirectories.setFrom(classDirectories.getFrom())
```

the build doesn't fail, but obviously the generated report is not a combined report, rather its just 
 a report of the last variant (reason for that is understandable from the code).

So there must be some problem in this merging part of class directories.

At first I thought that the problem is, that actually getting `mergedReportTask.classDirectories.getFrom()` returns collection of collections, while `classDirectories.getFrom()` returns simple collection.

I've attempted to flatten it, that didn't help. I have also noticed, that despite flattening, same collection would appear there over and over again (despite `classDirectories.setFrom` accepting a `Set`). (Or at least it appears as the same collection, having the same `displayName`)

I thought maybe the problem is in incorrect identification of unique collections, so I wrote this hacky code to see if it helps:

```
def merged = (classDirectories.getFrom() + mergedReportTask.classDirectories.getFrom().flatten())
                        .unique { m ->
                            if (m instanceof DefaultConfigurableFileCollection) {
                                println("PATH: ${(m as DefaultConfigurableFileCollection).displayName}")
                                return (m as DefaultConfigurableFileCollection).displayName
                            }
                            println("TREE: ${(m as DefaultConfigurableFileTree).displayName}")
                            (m as DefaultConfigurableFileTree).displayName
                        }
                println("MERGED (${merged.size()}): $merged")
                mergedReportTask.classDirectories.setFrom(merged)
```

The build itself doesn't fail now. Maybe that's good, maybe not. I don't know. Unfortunately the merged html report is actually empty. And here I'm at my wits' end.

Any pointer would be very helpful.

Also, if it helps, this is how the print of my `merged` property looks like:
```
MERGED (4): [directory 'path/core/build', directory 'path/common/build', directory 'path/app/build', file collection]
```
But you can see this line: `mergedReportTask.classDirectories.setFrom(merged)`. When printing `println("${mergedReportTask.classDirectories.getFrom()}")` it looks like this, when printed:

```
[[directory 'path/core/build', directory 'path/common/build', directory 'path/app/build', file collection]]
```

The thing that looks funny to me in that second output is, that now it's a collection within collection. Which... maybe it's correct, I don't know, I don't understand internals of Jacoco that well.

Any ideas? :-)

**Comment by vanniktech** [comment] 2020-03-30 06:43
No idea's no. Maybe this is a bug in the Jacoco API that we're using? In the end we're just delegating but not having an actual implementation.

**Comment by lukas1** [comment] 2020-03-30 07:11
ok, I'll see when I have time to work on this again and I'll try to bother some more people ;o)

**Comment by vanniktech** [comment] 2020-03-30 08:10
Sorry that I could not help more. To be honest, I've also mostly stopped using this plugin myself. I have it in my open source projects but that's about it.

**Comment by johnjohndoe** [comment] 2020-05-13 19:36
@vanniktech What are you using instead?

**Comment by vanniktech** [comment] 2020-05-14 06:31
Stopped caring about code coverage mostly. My open source projects are still using this project but that's about it.
